### PR TITLE
SonyMiner

### PR DESCRIPTION
**Pull request by sonyminer**
Great proyect!! New to this things but trying learn and wanting to share TouchBar preset

Main TouchBar - Web group, Dock, Apps direct access, Battery, Date and Time, Weather, Media group, Time group, Currency group
0 Main TouchBar

Web bookmarks Group
1 WWW Folder

Media Group - Sound, music and brightness controls 
2 Media

Time Group - with timer and world time
3 Time

Currency and Crypto Group - Some coins and currencies
4 Cryto Folder

Not a programer, but having fun with this customisation. Hope you like it and gives some ideas to others.

### CODE REVIEW

**Comment by Toxblh** [comment]
Brilliant!
Pls could you add also to readme links to your file.

**Comment by sonyminer** [comment]
Hello, not sure how to do it. Could yo help me? I am new to this and having trouble understanding the process.

Regards,

**Comment by sonyminer** [comment]
Hello Anton,

I am totally lost, not sure what I did, hopefully nothing too bad. 

I havre created this repositories (see screenshot).

Not sure what is the next step and where do I edit the Readme file. Do yo mean my readme file or the one in MTMR-presets…?

Regards,

**Comment by sonyminer** [comment]
Thanks. Now I figured out where to Edit the file. Still don’t know how to add a folder so the the json file is organized as the rest (in folders). I see I can upload files, I guess that is what I did, but no folders.

**Pull request merged**
